source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'RockSchedule_Example' do
  pod 'RockSchedule', :path => '../'

  target 'RockSchedule_Tests' do
    inherit! :search_paths

    
  end
end
